base_url = "https://zola-hallo.janbaudisch.dev"
title = "Hallo"

compile_sass = true

highlight_code = false

build_search_index = false

[extra]
greeting = "Hello!"

iam = "I am Wentao"

links = [
    { title = "E-Mail", url = "mailto:zwt2000sg@outlook.com", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com/taoo0316", icon = "github" }
]

[extra.author]
name = "Hallo"

[extra.theme]
background = "#6FCDBD"
foreground = "#FFF"
hover = "#333"
